apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis-exporter
  podMetricsEndpoints:
    - port: web

# Установите prometheus operator в ваш кластер в namespace `monitoring`.
# Запустите pod `redis-pod` в namespace `default` с двумя контейнерами — redis & redis-exporter.
# Создайте podmonitor `redis-monitor` в namespace `default`, чтобы prometheus он собирал данные с redis-exporter.
# Добавьте в графану dashboard, который будет выводить количество операций в секунду в редисе.
