apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-label
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: nginx
      nodeSelector:
        usercase: workload
#### end
 # Добавьте всем нодам в кластере label `usercase=workload`.
 # Добавьте на одну ноду taint `dedicted=true` noSchedule.
 # Создайте deployment `dp-label`, который будет запускать поды на нодах с label `usercase=workload`, и укажите количество реплик — 5 штук.
 # Создайте deployment `dp-taint`, который будет запускать поды на нодах с label `usercase=workload`, и toleration, который удовлетворяет условию dedicated=true.
