apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mf
  annotations:
    prometheus.io/scrape: "true"
  labels:
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:80
            initialDelaySeconds: 5
            periodSeconds: 5
#### end

#  Добавьте liveness probe http на порт 80 с произвольными значениями period & delay.
#  Добавьте readiness probe command с вызовом curl http://127.0.0.1:80.
