apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
spec:
  rules:
    - host: test.ingress.rebrainme.com
      http:
        paths:
          - backend:
              serviceName: svc-internal
              servicePort: 80

  # Создайте deployment с nginx `nginx-dp` в namespace `default`.
  # Создайте сервис для `nginx-dp` с именем `svc-internal` в namespace `default` с типом ClusterIP.
  # Создайте ingress `nginx-ingress` в namespace `default` для доменного имени `test.ingress.rebrainme.com`.
