apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-own-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
    nginx.ingress.kubernetes.io/auth-secret-type: "auth-file"
    # Указываем, каким образом выписывать сертификат
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: fedornabilkin.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-svc-ext
              servicePort: 80
  # Указываем настройки для tls — для какого хоста нужен tls и куда сохранить полученный сертификат
  tls:
    - hosts:
        - fedornabilkin.tk
      secretName: fedornabilkin-tk-cert
