apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-test
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpine
              image: alpine
              command: [ "/bin/sh" ]
              args: [ "-c", "apk --no-cache add curl", "curl https://lk.rebrainme.com/kubernetes/report" ]
