apiVersion: v1
kind: Pod
metadata:
  name: redis-kv
  namespace: stage
  labels:
    app: redis
spec:
  containers:
    - image: redis
      name: redis
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do sleep 300; done" ]
    - image: redis
      name: redis-exporter
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 300; done"]

### end
